---
title: "Testing Functions"
author: "Group2-Jing Lin, Yael Yossefy, Yaqian Han"
format: html
editor: visual
---
```{r,echo=FALSE}
knitr::opts_chunk$set(cache=TRUE, error=FALSE, message=FALSE, warning=FALSE,
                      echo=T, tidy.opts=list(width.cutoff=60),tidy=TRUE)

```

## Function 1

Function 1: Write a function that makes a boxplot of payments by DRG code. Make it an option for your function to do this for either the average Medicare payments, the average total payment, or the average covered charges

```{r load libraries}
library(ggplot2)
library(dplyr)
library(lab2group2package)
```

```{r load data}
DRG_data <- read.csv("DRG_data.csv")
```

```{r}
# Testing boxplot_function
boxplot_function(DRG_data, "medicare")
```

```{r}
# Calculate the mean 
mean_payment <- summary_function(DRG_data, "mean")
print(paste("Mean of average Medicare payments:", mean_payment))

# Testing median 
median_payment <- summary_function(DRG_data, "median")
print(paste("Median of average Medicare payments:", median_payment))

# Testing standard deviation
sd_payment <- summary_function(DRG_data, "sd")
print(paste("Standard deviation of average Medicare payments:", sd_payment))

```
